### ISSUE TITLE
trinityrnaseq_gnupar container image conversion to singularity

### ISSUE THREAD

**Issue by rsuchecki** [marcodelapierre/trinity-nf#1]
Hi Marco,

I am having some issues converting trinityrnaseq_gnupar docker image to a singularity one on our cluster. While I am able to do the singularity pull on a local machine and can use the generated sif image on the cluster, I wonder if you could share the Dockerfile used to generate the image?  Is that "just" Trinity + GNU parallel? 

Many thanks,

Rad

**Comment by marcodelapierre** [comment]
Hi Rad,

yep I just added GNU Parallel on top of the trinity image:
https://github.com/marcodelapierre/md-dockerfiles/blob/master/bio/trinity%2Bgnuparallel/Dockerfile

Hope this helps!

**Comment by rsuchecki** [comment]
Thanks Marco - I may try an alternative build then 👍
